config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'rooms/check_bookings'

  resources :rooms do
    resources :amenities
  end

  devise_for :users
  resources :images
  resources :bookings
  resources :reviews
  resources :cities
  
  root 'rooms#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/amenity.rb
class Amenity < ApplicationRecord

	belongs_to :room
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
	self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
	validates_presence_of :user_id,:room_id,:start_date,:end_date
	belongs_to :room
	belongs_to :user
end

app/models/city.rb
class City < ApplicationRecord

	has_many :rooms
end

app/models/image.rb
class Image < ApplicationRecord
	mount_uploader :cover, CoverUploader
	belongs_to :room
end

app/models/review.rb
class Review < ApplicationRecord

	belongs_to :user
	belongs_to :room
end

app/models/room.rb
class Room < ApplicationRecord

	validates_presence_of :name,:description,:price,:rules,:minimum_days,:address,:city

	belongs_to :city
	belongs_to :user
	has_many :images
	after_save :update_guest_to_host
	after_destroy :update_host_to_guest
	has_many :amenities
	has_many :bookings
	has_many :reviews
	private

	def update_guest_to_host
		user = self.user
		if user.user_role.name == "guest"
			user.user_role_id = 2
			user.save
		end
	end

	def update_host_to_guest
		user = self.user
		if user.user_role.name == "host" && user.rooms.count == 0
			user.user_role_id = 3
			user.save
		end
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   belongs_to :user_role
   has_many :rooms
   has_many :bookings
   has_many :reviews
end

app/models/user_role.rb
class UserRole < ApplicationRecord

	has_many :users
end

app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController

	def new
		@room = Room.find(params[:room_id])
		@amenity = Amenity.new
	end

	def create
		@room = Room.find(params[:room_id])
		@amenity = Amenity.new(amenity_params)
		if @amenity.save
			redirect_to room_path(@room) ,notice: 'saved amenity'
		end
	end

	private

	def amenity_params
		params[:amenity].permit(:name,:description,:room_id)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email,:username,:first_name,:last_name,:mobile_number,:user_role_id])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def index
		@bookings = Booking.where(:room_id => params[:room_id],:is_confirmed => false)
	end

	def new
		@booking = Booking.new
	end

	def create
		@booking = Booking.new(booking_params)
		@booking.user_id = current_user.id
		@booking.save
	end

	def update
		@booking = Booking.find(params[:id])
			if @booking.is_confirmed == false
				@booking.is_confirmed = true
				@booking.save
			end
		@bookings = Booking.where(:room_id => @booking.room_id, :is_confirmed => false)
	end

	private

	def booking_params
		params[:booking].permit(:start_date,:end_date,:room_id)
	end
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

	def create
		@image = Image.new(image_params)
		@image.save
	end


	private

	def image_params
		params[:image].permit(:photo,:room_id)
	end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController


	def index
		@reviews = Review.where('room_id = ?',params[:room_id])
	end
	
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all #where('is_authorized = ?' , true)
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  def check_bookings
    room = Room.find(params[:room_id])
    @bookings = room.bookings
  end
  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
      @booking = Booking.new
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:name, :description, :price, :rules, :minimum_days, :address, :latitude, :longitude, :is_authorized, :city_id, :user_id)
    end
end

app/helpers/amenities_helper.rb
module AmenitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/amenities/new.html.erb
<h2>Add new Amenity for <%= @room.name %></h2>
	
	<%= form_for [@room,@amenity] do |f| %>
	
	 <div class="field">
    <%= f.label :Name %><br>
    <%= f.text_field :name %>
 	 </div>

 	<div class="field">
    <%= f.label :Description %><br>
    <%= f.text_area :description %>
  	</div>

  	<%= f.hidden_field :room_id , value: @room.id %>
  	<div class="field">
  		<%= f.submit %>
  	</div>

	<% end %>

app/views/bookings/_form.html.erb
<%= form_for @booking,remote: true do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.text_field :start_date , id: "from" %>
  </div>

  <div class="field">
    <%= f.label :end_date %><br>
    <%= f.text_field :end_date, id: "to" %>
  </div>

    <%= f.hidden_field :room_id, value: @room.id %>
    
  <div class="actions">
    <%= f.submit "Book" %>
  </div>

  <% end %>

app/views/bookings/_table.html.erb
<% if @bookings.empty? %>
	<br>
	<strong>No Bookings pending.</strong>
<% else %>
	<br>
	<strong>Bookings pending (<%= @bookings.count %>)</strong>
	<% @bookings.each do |booking,index| %>
		<li id="<%= booking.id %>"><%= booking.start_date %> (<%= booking.user.username %>)- <%= link_to "confirm booking", booking_path(booking) ,method: :patch ,remote: true ,data: {confirm: 'Are you sure?'}%></li>
		<% end %>
<% end %>

app/views/bookings/create.js.erb
$("#form").empty();
var text = document.createTextNode("Please wait for your booking confirmation.");
$("#form").append(text);

app/views/bookings/index.js.erb
$('#booking').empty();
$('#booking').append("<%= escape_javascript (render  'table') %>");

app/views/bookings/update.js.erb
$('#booking').empty();
$('#booking').append("<%= escape_javascript (render  'table') %>");
$("#<%= @booking.id %>").slideUp();

app/views/reviews/_form.html.erb
<h3>Add review</h3>
<% @review = Review.new %>
<%= form_for @review,remote: true do |f| %>

  <div class="display" >
    <%= f.label :food %>(<span id="showFood" class="glyphicon glyphicon-star"></span>)<br>
    <%= f.hidden_field :food, id: 'food' %>
    <div class="slider" id="first"></div>
  </div>


  <div class="display">
  <%= f.label :safety %>(<span id="showSafety" class="glyphicon glyphicon-star"></span>)<br>
  <%= f.hidden_field :safety, id: 'safety' %>
    <div class="slider" id="second"></div>
  </div>

  <div class="display">
  <%= f.label :cleanliness %>(<span id="showCleanliness" class="glyphicon glyphicon-star"></span>)<br>
  <%= f.hidden_field :cleanliness, id: 'cleanliness' %>
    <div class="slider" id="second"></div>
  </div>

  <div class="display">
  <%= f.label :facility %>(<span id="showFacility" class="glyphicon glyphicon-star"></span>)<br>
  <%= f.hidden_field :facility ,id: 'facility' %>
    <div class="slider" id="second"></div>
  </div>

  <div class="display">
  <%= f.label :locality %>(<span id="showLocality" class="glyphicon glyphicon-star"></span>)<br>
  <%= f.hidden_field :locality, id: 'locality' %>
    <div class="slider" id="second"></div>
  </div>

  <%= f.submit "Add review"%>
<% end %>
 
<script>

  $( function() {
    $('div[class="slider"]').each(function(){
      $(this).slider({
        range: "max",
        min: 1.0,
        max: 5.0,
        step: 0.1,
        value: 1.0,
        slide: function( event, ui ) {
        $( "#food" ).val( ui.value );
        $('#showFood').text(ui.value);
        }
      });

    });

  });

  </script>

app/views/reviews/_table.html.erb
<% if @reviews.empty? %>
	<br>
	<strong>No reviews yet.</strong>
<% else %>
	<strong>Listing Reviews</strong>
	<% @reviews.each do |review| %>
	<li><%= review.body %></li>
	<% end %>
<% end %>
<br>
<%= render 'form' %>

app/views/reviews/index.js.erb
$('#reviews').append("<%= escape_javascript render 'table' %>");

app/views/rooms/_form.html.erb
<%= form_for(@room) do |f| %>
  <% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :rules %><br>
    <%= f.text_area :rules %>
  </div>
  <div class="field">
    <%= f.label :minimum_days %><br>
    <%= f.select :minimum_days , [1,2,3,4,5]%>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="field">
    <%= f.label :city_id %><br>
    <%= f.collection_select :city_id , City.all , :id , :name %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<div id="map">

</div>

<script>
  
  var handle = document.getElementById('room_address');

  handle.onblur = function(){
    if(handle.value != ""){
      $("#map").empty();
      var address = handle.value.split(" ");
      var send_address = address.join("+");
      $.ajax({url: "https://maps.googleapis.com/maps/api/geocode/json?address= " + send_address + "&key=AIzaSyBVRodsY3C5yOKnjSO9vYwWs8lfglebDTc", success: function(result){
        var res =  result["results"][0]["geometry"]["location"];
        var lat = res.lat;
        var long = res.lng;
        $("#room_latitude")[0].value = lat;
        $("#room_longitude")[0].value = long;
      }});
    }
  };
</script>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Rooms</h1>

<table class="table table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Rules</th>
      <th>Minimum days</th>
      <th>Address</th>
      <th>City</th>
      <th>Posted by</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.name %></td>
        <td><%= room.description %></td>
        <td><%= room.price %></td>
        <td><%= room.rules %></td>
        <td><%= room.minimum_days %></td>
        <td><%= room.address %></td>
        <td><%= room.city.name %></td>
        <td><%= room.user.username %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<div class="container">
<div class="col-md-6">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @room.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @room.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @room.price %>
</p>

<p>
  <strong>Rules:</strong>
  <%= @room.rules %>
</p>

<p>
  <strong>Minimum days:</strong>
  <%= @room.minimum_days %>
</p>

<p>
  <strong>Address:</strong>
  <%= @room.address %>
</p>

<p>
  <strong>Latitude:</strong><span id='latitude'><%= @room.latitude %></span>
</p>

<p>
  <strong>Longitude:</strong><span id='longitude'><%= @room.longitude %></span>
</p>

<div id="form">
<%= render './bookings/form' %>
</div>
<br>
<%= link_to 'new ammenity' , new_room_amenity_path(@room) %>|
<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>

<% if @room.amenities != nil %> 
  <% @room.amenities.each do |amenity| %>
  <span><%= amenity.name %></span>
  <p><%= amenity.description %></p>
  <% end %>
<% end %>

<!-- bookings div -->
<div id="booking">
<% if @room.user.id == current_user.id %>
  <button id="bookings" class="btn btn-small">Get Pending Bookings</button>
<% end %>
</div>
<!-- closing booking div -->

<!-- reviews div -->
<div id="reviews">
  
</div>
<!-- closing review div -->

</div>
<!-- closing left div-->

<!-- map div -->
<div class="col-md-6" id="map">
</div>
<!-- closing map div -->

</div>
<!-- closing container div -->
 <script>
  var dates = [];
    $( function() {
    var dateFormat = "mm/dd/yy",
      from = $( "#from" )
        .datepicker({
          minDate: 0,
          dateFormat: "yy-mm-dd",
          defaultDate: "+1w",
          changeMonth: true,
          numberOfMonths: 2,
          beforeShowDay: function(date){
            if($.inArray($.datepicker.formatDate('yy-mm-dd',date),dates) > -1){
              return [false,"","booked"];
            }
            return [true,"","available"];
          }
        })
        ,
      to = $( "#to" ).datepicker({
        minDate: 0,
        dateFormat: "yy-mm-dd",
        defaultDate: "+1w",
        changeMonth: true,
        numberOfMonths: 2,
        beforeShowDay: function(date){
            if($.inArray($.datepicker.formatDate('yy-mm-dd',date),dates) > -1){
              return [false,"","booked"];
            }
            return [true,"","available"];
          }
      }
   )
    });

  $(document).ready(function(){
    $.get("/rooms/check_bookings?room_id=<%= @room.id %>",function(result){
      result.forEach(function(obj){
        var sd = new Date(obj["booking"].start_date);
        var ed = new Date(obj["booking"].end_date);
        while(sd <= ed){
          var date = "";
          date += sd.getFullYear();
          date += "-";
          if(sd.getMonth() < 10){ 
            date += "0";  
            date += (sd.getMonth() + 1);
            date += "-";
          }
          else{
          date += (sd.getMonth() + 1);
          date += "-";
        }
        if(sd.getDate() < 10){
          date += "0";
          date += sd.getDate();
        }
        else{
          date += sd.getDate();
        }
          dates.push(date);
          sd = new Date(sd.getTime() + 1000*60*60*24);
        }  
      })
    });

    $.get('/reviews?room_id=<%= @room.id %>');

    var i = document.createElement("iframe");
        i.width = "600";
        i.height = "450";
        i.frameborder="0";
        i.style = "border:0";
        i.src = "https://www.google.com/maps/embed/v1/place?key=AIzaSyCpQuBa3ss1V-pAiHv6YmhlxBiEixgqPPE&q=" + $("latitude").innerHTML + "," + $("longitude").innerHTML;
        console.log(i.src);
        i.allowfullscreen = true;
        $("#map")[0].appendChild(i);

        $("#bookings").click(function(){
          $.get('/bookings?room_id=<%= @room.id %>');
        });
  });
  </script>